import 'server-only'
import { cache } from 'react'
import { createSupabaseServerClient } from '@/lib/supabase/server'
import { validatePageForPublish } from './pageService'
import { pageSnapshotSchema, type PageSnapshot } from './types'

const ids={home:'00000000-0000-4000-8000-000000000101',about:'00000000-0000-4000-8000-000000000102',pathway:'00000000-0000-4000-8000-000000000103','get-involved':'00000000-0000-4000-8000-000000000104'} as const
// Written as schema input: fields with a zod `.default()` (imageId, imageAlt, eyebrow…)
// are omitted here and filled by the parse below, which also proves each fallback page
// is schema-valid at import time rather than at first render.
const fallbackPageInput:Record<string,unknown>={
  home:{pageId:ids.home,slug:'home',title:'Home',seoTitle:'Oberlin Engineering Club',seoDescription:'Build, learn, and engineer together at Oberlin.',ogMediaId:null,sections:[
    {stableKey:'hero',isVisible:true,type:'hero',layout:'split',eyebrow:'Oberlin Engineering Club',headline:'Build. Learn. Engineer Together.',body:'A student group at Oberlin for people who like building things, and for anyone weighing the 3-2 engineering pathway.',primaryCta:{label:'Get involved',href:'/get-involved'},secondaryCta:{label:'Explore projects',href:'/projects'}},
    {stableKey:'disciplines',isVisible:true,type:'discipline_grid',heading:'Members come from across the sciences.',items:[{name:'Mechanical',description:'CAD, machining, 3D printing, and testing parts that have to hold up.'},{name:'Electrical',description:'Circuits, microcontrollers, sensors, and power.'},{name:'Computing & AI',description:'Software, embedded code, and machine learning.'},{name:'Chemical & Materials',description:'Lab chemistry, materials testing, and process work.'},{name:'Robotics',description:'Mechanical, electrical, and software work on one moving thing.'},{name:'Civil & Environmental',description:'Water, infrastructure, and environmental monitoring.'}]},
    {stableKey:'projects',isVisible:true,type:'project_grid',eyebrow:'Build with us',heading:'What we are building',limit:6,featuredOnly:false},
    {stableKey:'events',isVisible:true,type:'event_list',eyebrow:'Meet & learn',heading:'Upcoming events',limit:4,upcomingOnly:true},
    {stableKey:'opportunities',isVisible:true,type:'opportunity_list',eyebrow:'Go further',heading:'Opportunities worth knowing about',limit:4,featuredOnly:true},
    {stableKey:'join',isVisible:true,type:'cta',tone:'cardinal',eyebrow:'OEC',heading:'You do not need experience to join.',body:'You do not need to be in the 3-2 program or already know what kind of engineer you want to become.',primaryCta:{label:'Get involved',href:'/get-involved'},secondaryCta:{label:'Learn about the club',href:'/about'}}
  ]},
  about:{pageId:ids.about,slug:'about',title:'About',seoTitle:'About OEC',seoDescription:'Why the Oberlin Engineering Club exists and how it works.',ogMediaId:null,sections:[
    {stableKey:'hero',isVisible:true,type:'hero',layout:'minimal',eyebrow:'About OEC',headline:'A club for students who build things.',body:'Members come from physics, chemistry, computer science, maths, and the 3-2 engineering pathway.',primaryCta:{label:'Join the club',href:'/get-involved'}},
    {stableKey:'mission',isVisible:true,type:'text_image',layout:'image_right',eyebrow:'Mission',heading:'Oberlin has no engineering major.',body:'It has a 3-2 pathway with Caltech, Case Western Reserve, Columbia, and Washington University in St. Louis. That leaves students interested in engineering scattered across departments with nowhere obvious to find each other. The club is meant to be that place.'},
    {stableKey:'principles',isVisible:true,type:'features_grid',eyebrow:'How we work',heading:'How the club runs.',body:'The founding group is writing things down so the next set of officers does not start over.',items:[{title:'Build together',body:'A project needs a lead, tools, a budget, and a safety plan before it starts.'},{title:'Document the work',body:'Teams leave behind project updates, decisions, and public demos.'},{title:'Open the doors',body:'Students from every major and experience level can participate.'},{title:'Stay accurate',body:'A proposal is labelled a proposal until the work is confirmed.'}]},
    {stableKey:'leaders',isVisible:true,type:'leadership_grid',eyebrow:'Founding team',heading:'Founding members',limit:8,currentOnly:true},
    {stableKey:'join',isVisible:true,type:'cta',tone:'charcoal',heading:'Help get the club started.',body:'Join a project, propose one, volunteer, or help lead a recurring part of the club.',primaryCta:{label:'Get involved',href:'/get-involved'}}
  ]},
  pathway:{pageId:ids.pathway,slug:'pathway',title:'3-2 Pathway',seoTitle:'3-2 Engineering Pathway',seoDescription:'A student-friendly starting point for Oberlin 3-2 engineering planning with official-source links.',ogMediaId:null,sections:[
    {stableKey:'hero',isVisible:true,type:'hero',layout:'minimal',eyebrow:'3-2 Engineering Pathway',headline:'Three years at Oberlin, two at an engineering school.',body:'You finish with a BA from Oberlin and an engineering degree from the partner school. The club keeps the official sources in one place; it does not replace advising.',primaryCta:{label:'Browse official-source resources',href:'/resources?category=3-2'}},
    {stableKey:'notice',isVisible:true,type:'quote',quote:'Use this page as a planning map, not as an admissions contract. Confirm prerequisites, deadlines, financial aid, degree requirements, and transfer details with Oberlin and the partner engineering school.',attribution:'Oberlin Engineering Club',role:'Student resource notice'},
    {stableKey:'timeline',isVisible:true,type:'project_timeline',heading:'How the three years usually go',items:[{label:'Year 1',title:'Start the sequence',body:'CHEM 101, PHYS 111, MATH 234, and CSCI 150 turn up on most 3-2 plans. Starting the maths and physics early is what keeps the rest possible.'},{label:'Year 2',title:'Compare the four schools',body:'Prerequisites differ by school and by engineering major, and some Oberlin courses run in only one semester. This is the year to find the collisions.'},{label:'Year 3',title:'Apply',body:'Check prerequisites, deadlines, and financial aid against each school’s current official pages.'},{label:'Transfer',title:'Sort out the move',body:'Housing, credit transfer, and aid all get settled directly with the partner school before you go.'}]},
    {stableKey:'questions',isVisible:true,type:'features_grid',heading:'Questions worth asking before you apply',body:'Requirements differ by school and change between years.',items:[{title:'Prerequisites',body:'Which courses and grades are required for the specific engineering major?'},{title:'Admission',body:'What is guaranteed, conditional, or competitive for the partner school?'},{title:'Financial aid',body:'How will aid change after leaving Oberlin?'},{title:'Degree timing',body:'What must be completed before transfer, and what happens if a course is missing?'},{title:'Housing & transition',body:'What should you plan for before arriving at the partner school?'},{title:'Advising',body:'Who at Oberlin and the partner school can confirm your individual plan?'}]},
    {stableKey:'cta',isVisible:true,type:'cta',tone:'cardinal',heading:'Ask the people who have done it.',body:'Compare notes with other students, then confirm anything that matters with Oberlin advising and the partner school.',primaryCta:{label:'See resources',href:'/resources?category=3-2'},secondaryCta:{label:'Get involved',href:'/get-involved'}}
  ]},
  'get-involved':{pageId:ids['get-involved'],slug:'get-involved',title:'Get Involved',seoTitle:'Get Involved',seoDescription:'Join the Oberlin Engineering Club.',ogMediaId:null,sections:[]}
}
export const fallbackPages:Record<string,PageSnapshot>=Object.fromEntries(Object.entries(fallbackPageInput).map(([slug,page])=>[slug,pageSnapshotSchema.parse(page)]))

export type PublishedPageRepository={getPublished(slug:string):Promise<PageSnapshot|null>}
const supabaseRepo:PublishedPageRepository={async getPublished(slug){if(!process.env.NEXT_PUBLIC_SUPABASE_URL||!process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)return fallbackPages[slug]??null;const s=await createSupabaseServerClient();const{data:page,error}=await s.from('pages').select('id,slug,published_version_id').eq('slug',slug).maybeSingle();if(error||!page?.published_version_id)return fallbackPages[slug]??null;const{data:version}=await s.from('page_versions').select('page_snapshot,sections_snapshot').eq('id',page.published_version_id).maybeSingle();if(!version)return fallbackPages[slug]??null;return validatePageForPublish({...(version.page_snapshot as object),pageId:page.id,slug:page.slug,sections:version.sections_snapshot})}}
export const getPublishedPageBySlug=cache(async(slug:string,repo:PublishedPageRepository=supabaseRepo)=>{const page=await repo.getPublished(slug);if(!page)throw new Error('PUBLIC_PAGE_NOT_FOUND');return page})

export type PublicNavigationItem={id?:string;label:string;destination:string;external?:boolean;sortOrder?:number}
export async function getPublishedNavigation():Promise<PublicNavigationItem[]>{if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return [['Home','/'],['About','/about'],['Projects','/projects'],['Events','/events'],['Opportunities','/opportunities'],['Resources','/resources'],['3-2 Pathway','/pathway'],['News','/news'],['Get Involved','/get-involved']].map(([label,destination],i)=>({label,destination,sortOrder:(i+1)*10}));const s=await createSupabaseServerClient();const{data}=await s.from('navigation_items').select('id,label,destination,external,sort_order').eq('publication_state','published').eq('visible',true).order('sort_order');return(data??[]).map(r=>({id:r.id,label:r.label,destination:r.destination,external:r.external,sortOrder:r.sort_order}))}
export async function getPublicSiteSettings(){
  const fallback={contact:{email:'engineering@oberlin.edu'},footer:{text:'Build • Learn • Engineer Together'},social:{instagram:'',linkedin:'',github:''},seo:{titlePattern:'%s · Oberlin Engineering Club',defaultOgMediaId:null as string|null},announcement:null as null|{text:string;href?:string},brand:{badgeUrl:null as string|null,horizontalUrl:null as string|null}}
  if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return fallback
  const s=await createSupabaseServerClient();const{data}=await s.from('site_settings').select('key,value').eq('publication_state','published').in('key',['contact','footer','social','seo','announcement','brand']);const map=Object.fromEntries((data??[]).map(r=>[r.key,r.value])) as Record<string,any>
  const brandIds=[map.brand?.badgeMediaId,map.brand?.horizontalMediaId].filter(Boolean) as string[];let brandMedia:Record<string,string>={};if(brandIds.length){const{data:media}=await s.from('media').select('id,public_url').in('id',brandIds);brandMedia=Object.fromEntries((media??[]).map(m=>[m.id,m.public_url]))}
  return{contact:{...fallback.contact,...(map.contact??{})},footer:{...fallback.footer,...(map.footer??{})},social:{...fallback.social,...(map.social??{})},seo:{...fallback.seo,...(map.seo??{})},announcement:map.announcement?.enabled?map.announcement:null,brand:{badgeUrl:map.brand?.badgeMediaId?brandMedia[map.brand.badgeMediaId]??null:null,horizontalUrl:map.brand?.horizontalMediaId?brandMedia[map.brand.horizontalMediaId]??null:null}}
}

export async function getCmsRenderContext(){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return{};const s=await createSupabaseServerClient();const[projects,events,opportunities,news,leaders,sponsors,media]=await Promise.all([
  s.from('projects').select('*').eq('publication_state','published').order('sort_order').limit(12),s.from('events').select('*').eq('publication_state','published').gte('start_at',new Date().toISOString()).order('start_at').limit(12),s.from('opportunities').select('*').eq('publication_state','published').order('deadline').limit(12),s.from('news_posts').select('*').eq('publication_state','published').order('published_at',{ascending:false}).limit(12),s.from('leaders').select('*').eq('publication_state','published').eq('current',true).order('sort_order').limit(12),s.from('sponsors').select('*').eq('publication_state','published').order('sort_order').limit(12),s.from('media').select('id,public_url,alt_text').limit(200)
]);return{projects:projects.data??[],events:events.data??[],opportunities:opportunities.data??[],news:news.data??[],leaders:leaders.data??[],sponsors:sponsors.data??[],media:Object.fromEntries((media.data??[]).map(m=>[m.id,{url:m.public_url,alt:m.alt_text}]))}}
