import type { Metadata } from 'next'
import { metadataForCmsPage } from '@/lib/seo/metadata'
import { getPublishedPageBySlug } from '@/lib/page-builder/publicPages'
import { DirectoryHero } from '@/components/public/DirectoryHero'
import { ResourceFilters } from '@/components/public/filters/ResourceFilters'
import { listPublishedPartnerSchools,listPublishedResources,parseResourceFilters } from '@/lib/content/resources'
function toParams(o:Record<string,string|string[]|undefined>){const p=new URLSearchParams();for(const[k,v]of Object.entries(o))if(typeof v==='string')p.set(k,v);return p}
export async function generateMetadata():Promise<Metadata>{return metadataForCmsPage(await getPublishedPageBySlug("resources"))}
export default async function ResourcesPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const f=parseResourceFilters(toParams(await searchParams));const[items,partners]=await Promise.all([listPublishedResources(f),f.category?.toLowerCase()==='3-2'?listPublishedPartnerSchools():Promise.resolve([])]);return <><DirectoryHero slug={"resources"} eyebrow={"Resources"} title={"Engineering resources"} description={"Official 3-2 information, partner-school pages, career resources, and tools for projects."} imageSlug={"resources-electronics-bench"}/><section className="directory"><div className="shell"><ResourceFilters category={f.category}/>{f.category?.toLowerCase()==='3-2'&&<div className="source-notice"><strong>3-2 source notice</strong><p>Club summaries are planning aids. Confirm requirements with Oberlin advisers and each partner institution’s current official pages.</p></div>}{partners.length>0&&<><h2>Partner-school official pages</h2><div className="card-grid">{partners.map((p:any)=><article className="content-card" key={p.id}><p className="eyebrow">Official source</p><h3>{p.name}</h3><p>{p.location}</p><a href={p.official_url} target="_blank" rel="noreferrer">Official program page ↗</a></article>)}</div></>}{items.length?<div className="resource-list">{items.map((r:any)=><article key={r.id}><div><div className="content-card__actions"><p className="eyebrow">{r.category}{r.official_source?' · Official source':''}</p></div><h2>{r.title}</h2><p>{r.description}</p></div>{(r.source_url||r.url)&&<a href={r.source_url||r.url} target="_blank" rel="noreferrer">Open resource ↗</a>}</article>)}</div>:partners.length===0&&<div className="empty-state"><h2>No resources in this category yet.</h2><p>More resources will be added as members find them.</p></div>}</div></section></>}
