import type { Metadata } from 'next'
import { metadataForCmsPage } from '@/lib/seo/metadata'
import { getPublishedPageBySlug } from '@/lib/page-builder/publicPages'
import { DirectoryHero } from '@/components/public/DirectoryHero'
import { SaveButton } from '@/components/member/SaveButton'
import { ResourceFilters } from '@/components/public/filters/ResourceFilters'
import { getCurrentMember } from '@/lib/auth/memberSession'
import { listPublishedPartnerSchools,listPublishedResources,parseResourceFilters } from '@/lib/content/resources'
import { getSavedItemIds } from '@/lib/members/saves'
function toParams(o:Record<string,string|string[]|undefined>){const p=new URLSearchParams();for(const[k,v]of Object.entries(o))if(typeof v==='string')p.set(k,v);return p}
export async function generateMetadata():Promise<Metadata>{return metadataForCmsPage(await getPublishedPageBySlug("resources"))}
export default async function ResourcesPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const f=parseResourceFilters(toParams(await searchParams));const[items,partners,member]=await Promise.all([listPublishedResources(f),f.category?.toLowerCase()==='3-2'?listPublishedPartnerSchools():Promise.resolve([]),getCurrentMember()]);const saved=member?await getSavedItemIds(member.userId,'RESOURCE',items.map((item:any)=>item.id)):new Set<string>();return <><DirectoryHero slug={"resources"} eyebrow={"Resources"} title={"Official sources and working tools."} description={"Oberlin's own 3-2 pages, the four partner schools, and tools members use."} imageSlug={"resources-electronics-bench"}/><section className="directory"><div className="shell"><ResourceFilters category={f.category}/>{f.category?.toLowerCase()==='3-2'&&<div className="source-notice"><strong>3-2 source notice</strong><p>Club summaries are planning aids. Confirm requirements with Oberlin advisers and each partner institution’s current official pages.</p></div>}{partners.length>0&&<><h2>Partner-school official pages</h2><div className="card-grid">{partners.map((p:any)=><article className="content-card" key={p.id}><p className="eyebrow">Official source</p><h3>{p.name}</h3><p>{p.location}</p><a href={p.official_url} target="_blank" rel="noreferrer">Official program page ↗</a></article>)}</div></>}{items.length?<div className="resource-list">{items.map((r:any)=><article key={r.id}><div><div className="content-card__actions"><p className="eyebrow">{r.category}{r.official_source?' · Official source':''}</p><SaveButton itemType="RESOURCE" itemId={r.id} canSave={Boolean(member)} initialSaved={saved.has(r.id)}/></div><h2>{r.title}</h2><p>{r.description}</p></div>{(r.source_url||r.url)&&<a href={r.source_url||r.url} target="_blank" rel="noreferrer">Open resource ↗</a>}</article>)}</div>:partners.length===0&&<div className="empty-state"><h2>No published resources match this category yet.</h2><p>More resources are on the way. Check back soon.</p></div>}</div></section></>}
