'use client'
import { FormEvent,useState } from 'react'
import type { MediaAsset } from '@/lib/cms/media'
import type { ImageSourceType } from '@/lib/media/imagePolicy'
import { getImagePublishBlockReason } from '@/lib/media/imagePolicy'

const reasonLabel={IMAGE_ALT_REQUIRED:'Needs alt text',LICENSED_IMAGE_RIGHTS_REQUIRED:'Needs license / rights details',GENERATED_IMAGE_QA_REQUIRED:'Needs human realism QA'} as const

function MetadataForm({asset,onSaved}:{asset:MediaAsset;onSaved:(asset:MediaAsset)=>void}){
  const[busy,setBusy]=useState(false)
  const[message,setMessage]=useState('')
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const fd=new FormData(event.currentTarget);setBusy(true);setMessage('');const body={id:asset.id,altText:String(fd.get('altText')??''),caption:String(fd.get('caption')??''),tags:String(fd.get('tags')??'').split(',').map(x=>x.trim()).filter(Boolean),sourceType:String(fd.get('sourceType')??'original') as ImageSourceType,rightsNote:String(fd.get('rightsNote')??''),focalX:fd.get('focalX')===''?null:Number(fd.get('focalX')),focalY:fd.get('focalY')===''?null:Number(fd.get('focalY')),visualQaApproved:fd.get('visualQaApproved')==='on'};const response=await fetch('/api/media',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(response.ok){onSaved(result.item);setMessage('Metadata saved.')}else setMessage(result.error??'Could not save metadata.');setBusy(false)}
  const blocked=getImagePublishBlockReason(asset)
  return <form className="media-metadata-form" onSubmit={save}><div className="media-status-row"><span className={`media-status ${blocked?'is-blocked':'is-ready'}`}>{blocked?reasonLabel[blocked]:'Publish-ready'}</span><span>{asset.sourceType}</span></div><label>Alt text<input name="altText" defaultValue={asset.altText} placeholder="Describe what matters in the image" /></label><label>Caption / credit<input name="caption" defaultValue={asset.caption} /></label><label>Tags<input name="tags" defaultValue={asset.tags.join(', ')} placeholder="robotics, workshop, students" /></label><label>Source<select name="sourceType" defaultValue={asset.sourceType}><option value="original">Original / OEC photo</option><option value="licensed">Licensed photo</option><option value="generated">Generated photo</option></select></label><label>Rights / provenance<textarea name="rightsNote" rows={2} defaultValue={asset.rightsNote??''} placeholder="Photographer, license/source, or generation provenance" /></label><div className="form-grid"><label>Focal X<input name="focalX" type="number" min="0" max="1" step="0.05" defaultValue={asset.focalX??''} /></label><label>Focal Y<input name="focalY" type="number" min="0" max="1" step="0.05" defaultValue={asset.focalY??''} /></label></div>{asset.sourceType==='generated'&&<label className="inline-check media-qa-check"><input name="visualQaApproved" type="checkbox" defaultChecked={asset.visualQaApproved}/>Human visual QA approved</label>}<p className="media-qa-note">For generated photography, inspect hands, tools, text, lighting, reflections, proportions, and textures at full size. Reject anything plastic, distorted, or obviously synthetic.</p><button type="submit" disabled={busy}>{busy?'Saving…':'Save metadata'}</button>{message&&<small role="status">{message}</small>}</form>
}

export function MediaLibrary({initialAssets}:{initialAssets:MediaAsset[]}){
  const[assets,setAssets]=useState(initialAssets);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('')
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);setBusy(true);setMessage('');const res=await fetch('/api/media',{method:'POST',body:fd});const body=await res.json();if(res.ok){setAssets(current=>[body.item,...current]);form.reset();setMessage('Uploaded. Add metadata before using the asset publicly.')}else setMessage(body.error??'Upload failed.');setBusy(false)}
  function replace(updated:MediaAsset){setAssets(current=>current.map(asset=>asset.id===updated.id?updated:asset))}
  return <div className="admin-panel"><div className="admin-panel__heading"><div><p className="eyebrow">Media Library</p><h1>Images & documents</h1><p>Upload once, record provenance, approve realistic generated photography, and reuse assets across the site.</p></div><form className="media-upload-form" onSubmit={upload}><label>Source<select name="sourceType" defaultValue="original"><option value="original">Original / OEC</option><option value="licensed">Licensed</option><option value="generated">Generated</option></select></label><label className="upload-button">{busy?'Uploading…':'Upload media'}<input name="file" type="file" accept="image/*,application/pdf" disabled={busy} required /></label></form></div>{message&&<p role="status">{message}</p>}<div className="admin-media-grid">{assets.map(asset=><article key={asset.id}>{asset.mimeType.startsWith('image/')?<img src={asset.publicUrl} alt={asset.altText}/>:<div className="file-tile">PDF</div>}<div className="media-card-heading"><strong>{asset.fileName}</strong><small>{asset.protected?'Protected brand asset':asset.mimeType}</small></div>{asset.mimeType.startsWith('image/')&&<MetadataForm key={`${asset.id}:${asset.sourceType}:${asset.visualQaApproved}`} asset={asset} onSaved={replace}/>}</article>)}</div></div>
}
