import { mkdir,readFile,writeFile } from 'node:fs/promises'
import path from 'node:path'
import { buildMigrationSafetyReport,mapLegacyDocument,mapLegacyEvent,mapLegacyLeader,mapLegacyMedia,mapLegacyNews,mapLegacyOpportunity,mapLegacyPartnerSchool,mapLegacyProject,mapLegacyProjectUpdate,mapLegacyResource,mapLegacySponsor,mapLegacySubmission } from '../lib/migration/legacyMappers.ts'
import { migrationTablePlan } from '../lib/migration/plan.ts'

type Row=Record<string,any>;type Dataset=Record<string,Row[]>
const args=process.argv.slice(2);const dryRun=args.includes('--dry-run');const fixtureIndex=args.indexOf('--fixture');const fixture=fixtureIndex>=0?args[fixtureIndex+1]:null
const legacyUrl=process.env.LEGACY_SUPABASE_URL?.replace(/\/$/,'');const legacyKey=process.env.LEGACY_SUPABASE_SERVICE_ROLE_KEY;const targetUrl=process.env.NEW_SUPABASE_URL?.replace(/\/$/,'');const targetKey=process.env.NEW_SUPABASE_SERVICE_ROLE_KEY
const authHeaders=(key:string)=>({apikey:key,authorization:`Bearer ${key}`})

async function fetchLegacyTable(table:string):Promise<Row[]>{if(!legacyUrl||!legacyKey)throw new Error('LEGACY_SUPABASE_CONFIG_MISSING');const response=await fetch(`${legacyUrl}/rest/v1/${table}?select=*`,{headers:authHeaders(legacyKey)});if(response.ok)return await response.json();if([400,404].includes(response.status)){console.warn(`Legacy table ${table} unavailable; recording zero rows.`);return[]}throw new Error(`LEGACY_READ_FAILED:${table}:${response.status}:${await response.text()}`)}
async function loadDataset():Promise<Dataset>{if(fixture)return JSON.parse(await readFile(path.resolve(fixture),'utf8'));const result:Dataset={};for(const item of migrationTablePlan)result[item.source]=await fetchLegacyTable(item.source);return result}
async function upsert(table:string,row:Row,conflict='legacy_source_id'):Promise<Row>{if(dryRun)return{id:`dry-${table}-${row.legacy_source_id??row.key??crypto.randomUUID()}`,...row};if(!targetUrl||!targetKey)throw new Error('NEW_SUPABASE_CONFIG_MISSING');const response=await fetch(`${targetUrl}/rest/v1/${table}?on_conflict=${encodeURIComponent(conflict)}`,{method:'POST',headers:{...authHeaders(targetKey),'content-type':'application/json',Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(row)});if(!response.ok)throw new Error(`TARGET_WRITE_FAILED:${table}:${response.status}:${await response.text()}`);const data=await response.json();return data[0]??row}
async function copyMedia(row:ReturnType<typeof mapLegacyMedia>):Promise<ReturnType<typeof mapLegacyMedia>>{if(dryRun||!row.public_url||!targetUrl||!targetKey)return row;const source=await fetch(row.public_url);if(!source.ok)throw new Error(`MEDIA_SOURCE_FETCH_FAILED:${row.legacy_source_id}:${source.status}`);const bytes=await source.arrayBuffer();const objectPath=`legacy/${row.legacy_source_id}-${row.file_name.replace(/[^a-zA-Z0-9._-]+/g,'-')}`;const upload=await fetch(`${targetUrl}/storage/v1/object/oec-media/${objectPath}`,{method:'POST',headers:{...authHeaders(targetKey),'content-type':row.mime_type||'application/octet-stream','x-upsert':'true'},body:bytes});if(!upload.ok)throw new Error(`MEDIA_COPY_FAILED:${row.legacy_source_id}:${upload.status}:${await upload.text()}`);return{...row,storage_path:objectPath,public_url:`${targetUrl}/storage/v1/object/public/oec-media/${objectPath}`,size_bytes:bytes.byteLength}}
function omit(row:Row,...keys:string[]){const copy={...row};for(const key of keys)delete copy[key];return copy}

const dataset=await loadDataset();const report:any={dryRun,generatedAt:new Date().toISOString(),tables:{},reviewOnly:{},rejected:[],idMap:{media:{},projects:{}},...buildMigrationSafetyReport({submissions:dataset.submissions??[],profiles:dataset.profiles??[]})}
for(const item of migrationTablePlan.filter(x=>x.mode==='review_only'))report.reviewOnly[item.source]=(dataset[item.source]??[]).map(row=>({id:row.id??null,reason:item.source==='profiles'?'Staff identities require authenticated-user review and a new Super Admin invitation.':'Legacy surface is outside launch scope and requires human review.'}))

async function migrateRows(source:string,target:string,mapper:(row:Row)=>Row,prepare?:(mapped:Row)=>Promise<Row|null>){let accepted=0;for(const raw of dataset[source]??[]){try{const mapped=mapper(raw);const ready=prepare?await prepare(mapped):mapped;if(!ready){report.rejected.push({table:source,id:raw.id??null,reason:'UNRESOLVED_REFERENCE'});continue}await upsert(target,ready);accepted++}catch(error){report.rejected.push({table:source,id:raw.id??null,reason:error instanceof Error?error.message:String(error)})}}report.tables[source]={source:(dataset[source]??[]).length,accepted,rejected:(dataset[source]??[]).length-accepted}}

for(const raw of dataset.media??[]){try{const mapped=await copyMedia(mapLegacyMedia(raw));const inserted=await upsert('media',mapped);report.idMap.media[mapped.legacy_source_id]=inserted.id;report.tables.media??={source:(dataset.media??[]).length,accepted:0,rejected:0};report.tables.media.accepted++}catch(error){report.rejected.push({table:'media',id:raw.id??null,reason:error instanceof Error?error.message:String(error)});report.tables.media??={source:(dataset.media??[]).length,accepted:0,rejected:0};report.tables.media.rejected++}}
for(const raw of dataset.projects??[]){try{const mapped:any=mapLegacyProject(raw);const legacyMedia=mapped.legacy_media_id;delete mapped.legacy_media_id;const note=mapped.migration_note;delete mapped.migration_note;if(legacyMedia)mapped.cover_media_id=report.idMap.media[legacyMedia]??null;const inserted=await upsert('projects',mapped);report.idMap.projects[mapped.legacy_source_id]=inserted.id;report.tables.projects??={source:(dataset.projects??[]).length,accepted:0,rejected:0};report.tables.projects.accepted++;if(note)(report.reviewOnly.project_status_notes??=[]).push({id:mapped.legacy_source_id,note})}catch(error){report.rejected.push({table:'projects',id:raw.id??null,reason:error instanceof Error?error.message:String(error)});report.tables.projects??={source:(dataset.projects??[]).length,accepted:0,rejected:0};report.tables.projects.rejected++}}
await migrateRows('project_updates','project_updates',mapLegacyProjectUpdate,async(mapped:any)=>{const projectId=report.idMap.projects[mapped.legacy_project_id];if(!projectId)return null;const ready=omit(mapped,'legacy_project_id','legacy_media_id');ready.project_id=projectId;ready.media_id=mapped.legacy_media_id?report.idMap.media[mapped.legacy_media_id]??null:null;return ready})
await migrateRows('events','events',mapLegacyEvent,async(mapped:any)=>{const ready=omit(mapped,'legacy_media_id');ready.cover_media_id=mapped.legacy_media_id?report.idMap.media[mapped.legacy_media_id]??null:null;return ready})
await migrateRows('leaders','leaders',mapLegacyLeader,async(mapped:any)=>{const ready=omit(mapped,'legacy_media_id');ready.photo_media_id=mapped.legacy_media_id?report.idMap.media[mapped.legacy_media_id]??null:null;return ready})
await migrateRows('news_posts','news_posts',mapLegacyNews,async(mapped:any)=>{const ready=omit(mapped,'legacy_media_id');ready.cover_media_id=mapped.legacy_media_id?report.idMap.media[mapped.legacy_media_id]??null:null;return ready})
await migrateRows('sponsors','sponsors',mapLegacySponsor,async(mapped:any)=>{const ready=omit(mapped,'legacy_media_id');ready.logo_media_id=mapped.legacy_media_id?report.idMap.media[mapped.legacy_media_id]??null:null;return ready})
await migrateRows('resources','resources',mapLegacyResource)
await migrateRows('opportunities','opportunities',mapLegacyOpportunity)
await migrateRows('partner_schools','partner_schools',mapLegacyPartnerSchool)
await migrateRows('documents','documents',mapLegacyDocument)
await migrateRows('submissions','submissions',mapLegacySubmission)

const safeSettingKeys=new Set(['contact','footer','social','announcement'])
let settingsAccepted=0;for(const row of dataset.site_settings??[]){if(!safeSettingKeys.has(String(row.key))){(report.reviewOnly.site_settings??=[]).push({key:row.key,reason:'Brand/SEO/unknown settings stay on the new reviewed defaults.'});continue}try{await upsert('site_settings',{key:String(row.key),value:row.value??{},publication_state:'published'},'key');settingsAccepted++}catch(error){report.rejected.push({table:'site_settings',id:row.key??null,reason:error instanceof Error?error.message:String(error)})}}
report.tables.site_settings={source:(dataset.site_settings??[]).length,accepted:settingsAccepted,rejected:(dataset.site_settings??[]).length-settingsAccepted}

await mkdir('artifacts/migration',{recursive:true});await writeFile('artifacts/migration/migration-report.json',JSON.stringify(report,null,2));await writeFile('artifacts/migration/migration-id-map.json',JSON.stringify(report.idMap,null,2));
console.log(JSON.stringify({dryRun,autoApprovedMembers:report.autoApprovedMembers,autoApprovedStaff:report.autoApprovedStaff,rejected:report.rejected.length,tables:report.tables},null,2))
if(report.autoApprovedMembers!==0||report.autoApprovedStaff!==0)throw new Error('MIGRATION_SECURITY_INVARIANT_BROKEN')
