import 'server-only'
import { createHash } from 'node:crypto'
import sharp from 'sharp'
import { createSupabaseServerClient } from '@/lib/supabase/server'
import { createSupabaseAdminClient } from '@/lib/supabase/admin'
import { assertPublishableImageMetadata,type ImageSourceType } from '@/lib/media/imagePolicy'

export type MediaAsset={
  id:string;fileName:string;storagePath:string;publicUrl:string;mimeType:string;sizeBytes:number;altText:string;caption:string;tags:string[];
  width:number|null;height:number|null;protected:boolean;contentHash:string|null;sourceType:ImageSourceType;rightsNote:string|null;
  focalX:number|null;focalY:number|null;visualQaApproved:boolean
}
export type MediaValidation={ok:true}|{ok:false;reason:'UNSUPPORTED_TYPE'|'FILE_TOO_LARGE'}
export type MediaMetadataInput={altText:string;caption?:string;tags?:string[];sourceType?:ImageSourceType;rightsNote?:string|null;focalX?:number|null;focalY?:number|null;visualQaApproved?:boolean}
const allowed=new Set(['image/png','image/jpeg','image/webp','image/gif','application/pdf'])
const sourceTypes=new Set<ImageSourceType>(['original','licensed','generated'])
const MAX_SIZE=15*1024*1024
export function validateMediaUpload({mime,size}:{mime:string;size:number}):MediaValidation{if(!allowed.has(mime))return{ok:false,reason:'UNSUPPORTED_TYPE'};if(size>MAX_SIZE)return{ok:false,reason:'FILE_TOO_LARGE'};return{ok:true}}
function validateSourceType(value:unknown):ImageSourceType{if(typeof value==='string'&&sourceTypes.has(value as ImageSourceType))return value as ImageSourceType;throw new Error('INVALID_MEDIA_SOURCE_TYPE')}
function validateFocal(value:number|null|undefined){if(value==null)return null;if(!Number.isFinite(value)||value<0||value>1)throw new Error('INVALID_FOCAL_POINT');return value}
const map=(r:any):MediaAsset=>({id:r.id,fileName:r.file_name,storagePath:r.storage_path,publicUrl:r.public_url,mimeType:r.mime_type,sizeBytes:Number(r.size_bytes),altText:r.alt_text,caption:r.caption,tags:r.tags??[],width:r.width,height:r.height,protected:Boolean(r.protected),contentHash:r.content_hash,sourceType:r.source_type??'original',rightsNote:r.rights_note??null,focalX:r.focal_x==null?null:Number(r.focal_x),focalY:r.focal_y==null?null:Number(r.focal_y),visualQaApproved:Boolean(r.visual_qa_approved)})
export async function listMedia(query=''):Promise<MediaAsset[]>{const s=await createSupabaseServerClient();let q=s.from('media').select('*').order('created_at',{ascending:false}).limit(100);if(query.trim())q=q.ilike('file_name',`%${query.trim()}%`);const{data,error}=await q;if(error)throw new Error(`MEDIA_LIST_FAILED:${error.message}`);return(data??[]).map(map)}
export async function getMediaUsage(mediaId:string){const s=await createSupabaseServerClient();const{data,error}=await s.from('media_usage').select('owner_type,owner_id,field_key').eq('media_id',mediaId);if(error)throw new Error(`MEDIA_USAGE_FAILED:${error.message}`);return data??[]}
export async function updateMediaMetadata(id:string,input:MediaMetadataInput):Promise<MediaAsset>{const s=await createSupabaseServerClient();const sourceType=input.sourceType?validateSourceType(input.sourceType):undefined;const patch:any={alt_text:input.altText,caption:input.caption??'',tags:input.tags??[]};if(sourceType)patch.source_type=sourceType;if(input.rightsNote!==undefined)patch.rights_note=input.rightsNote?.trim()||null;if(input.focalX!==undefined)patch.focal_x=validateFocal(input.focalX);if(input.focalY!==undefined)patch.focal_y=validateFocal(input.focalY);if(input.visualQaApproved!==undefined)patch.visual_qa_approved=Boolean(input.visualQaApproved);if(sourceType&&sourceType!=='generated')patch.visual_qa_approved=false;const{data,error}=await s.from('media').update(patch).eq('id',id).select('*').single();if(error||!data)throw new Error(`MEDIA_UPDATE_FAILED:${error?.message??'unknown'}`);return map(data)}
export async function uploadMedia(file:File,actorId:string,metadata?:{sourceType?:ImageSourceType}):Promise<MediaAsset>{const check=validateMediaUpload({mime:file.type,size:file.size});if(!check.ok)throw new Error(check.reason);const sourceType=metadata?.sourceType?validateSourceType(metadata.sourceType):'original';const bytes=Buffer.from(await file.arrayBuffer());const hash=createHash('sha256').update(bytes).digest('hex');let width:number|null=null,height:number|null=null;if(file.type.startsWith('image/')){try{const meta=await sharp(bytes).metadata();width=meta.width??null;height=meta.height??null}catch{throw new Error('INVALID_IMAGE')}}const s=await createSupabaseServerClient();const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'upload';const path=`${new Date().getUTCFullYear()}/${crypto.randomUUID()}-${safe}`;const{error:uploadError}=await s.storage.from('oec-media').upload(path,bytes,{contentType:file.type,upsert:false});if(uploadError)throw new Error(`MEDIA_UPLOAD_FAILED:${uploadError.message}`);const publicUrl=s.storage.from('oec-media').getPublicUrl(path).data.publicUrl;const{data,error}=await s.from('media').insert({file_name:file.name,storage_path:path,public_url:publicUrl,mime_type:file.type,size_bytes:file.size,width,height,content_hash:hash,uploaded_by:actorId,source_type:sourceType,visual_qa_approved:false}).select('*').single();if(error||!data){await s.storage.from('oec-media').remove([path]);throw new Error(`MEDIA_METADATA_FAILED:${error?.message??'unknown'}`)}return map(data)}
export async function assertPublishableMediaIds(ids:string[],useAdmin=false):Promise<void>{if(!ids.length)return;const unique=[...new Set(ids)];const s=useAdmin?createSupabaseAdminClient():await createSupabaseServerClient();const{data,error}=await s.from('media').select('id,mime_type,alt_text,source_type,rights_note,visual_qa_approved').in('id',unique);if(error)throw new Error(`MEDIA_VALIDATION_FAILED:${error.message}`);const rows=data??[];const found=new Set(rows.map((row:any)=>row.id));if(unique.some(id=>!found.has(id)))throw new Error('MEDIA_NOT_FOUND');for(const row of rows){assertPublishableImageMetadata({mimeType:row.mime_type,altText:row.alt_text??'',sourceType:(row.source_type??'original') as ImageSourceType,rightsNote:row.rights_note??null,visualQaApproved:Boolean(row.visual_qa_approved)})}}
export async function deleteMedia(id:string){const s=await createSupabaseServerClient();const{data,error}=await s.from('media').select('*').eq('id',id).single();if(error||!data)throw new Error('MEDIA_NOT_FOUND');if(data.protected)throw new Error('PROTECTED_MEDIA');const usage=await getMediaUsage(id);if(usage.length)throw new Error('MEDIA_IN_USE');const{error:storageError}=await s.storage.from('oec-media').remove([data.storage_path]);if(storageError)throw new Error(`MEDIA_DELETE_FAILED:${storageError.message}`);const{error:rowError}=await s.from('media').delete().eq('id',id);if(rowError)throw new Error(`MEDIA_DELETE_FAILED:${rowError.message}`)}
