import { createSupabaseServerClient } from '@/lib/supabase/server'

export type RedirectRuleInput={id?:string;sourcePath:string;destination:string;statusCode:301|302|307|308;active:boolean}
export type RedirectRule=Required<RedirectRuleInput>&{updatedAt?:string}
const allowedCodes=new Set([301,302,307,308])
function safeDestination(value:string){const destination=value.trim();if(!destination||/^\s*(javascript|data|vbscript):/i.test(destination))throw new Error('UNSAFE_DESTINATION');if(destination.startsWith('/')&&!destination.startsWith('//'))return destination;let url:URL;try{url=new URL(destination)}catch{throw new Error('UNSAFE_DESTINATION')}if(!['http:','https:'].includes(url.protocol))throw new Error('UNSAFE_DESTINATION');return url.toString()}
export function validateRedirectInput(input:unknown):Omit<RedirectRuleInput,'id'>&{id?:string}{if(!input||typeof input!=='object')throw new Error('INVALID_REDIRECT');const raw=input as Record<string,unknown>;const sourcePath=String(raw.sourcePath??'').trim();if(!sourcePath.startsWith('/')||sourcePath.startsWith('//')||sourcePath.includes('?')||sourcePath.length>500)throw new Error('INVALID_SOURCE_PATH');const code=Number(raw.statusCode);if(!allowedCodes.has(code))throw new Error('INVALID_STATUS_CODE');return{id:typeof raw.id==='string'?raw.id:undefined,sourcePath,destination:safeDestination(String(raw.destination??'')),statusCode:code as 301|302|307|308,active:raw.active!==false}}
export async function listRedirects():Promise<RedirectRule[]>{const s=await createSupabaseServerClient();const{data,error}=await s.from('redirect_rules').select('id,source_path,destination,status_code,active,updated_at').order('source_path');if(error)throw new Error(`REDIRECTS_LOAD_FAILED:${error.message}`);return(data??[]).map(row=>({id:row.id,sourcePath:row.source_path,destination:row.destination,statusCode:row.status_code,active:row.active,updatedAt:row.updated_at}))}
export async function saveRedirect(input:unknown,actorId:string){const rule=validateRedirectInput(input);const s=await createSupabaseServerClient();// Built as one optional-field shape rather than a union of two shapes, which the
// upsert overloads reject.
const payload:{source_path:string;destination:string;status_code:301|302|307|308;active:boolean;updated_by:string;id?:string;created_by?:string}={source_path:rule.sourcePath,destination:rule.destination,status_code:rule.statusCode,active:rule.active,updated_by:actorId};
if(rule.id)payload.id=rule.id;else payload.created_by=actorId;const{data,error}=await s.from('redirect_rules').upsert(payload,rule.id?{onConflict:'id'}:{onConflict:'source_path'}).select('id').single();if(error)throw new Error(`REDIRECT_SAVE_FAILED:${error.message}`);await s.from('audit_log').insert({actor_id:actorId,action:'REDIRECT_SAVED',entity_type:'redirect',entity_id:data.id,after_snapshot:rule});return data.id as string}
export async function deleteRedirect(id:string,actorId:string){const s=await createSupabaseServerClient();const{data}=await s.from('redirect_rules').select('*').eq('id',id).single();const{error}=await s.from('redirect_rules').delete().eq('id',id);if(error)throw new Error(`REDIRECT_DELETE_FAILED:${error.message}`);await s.from('audit_log').insert({actor_id:actorId,action:'REDIRECT_DELETED',entity_type:'redirect',entity_id:id,before_snapshot:data??{}})}
export async function resolveRedirect(sourcePath:string):Promise<RedirectRule|null>{if(!process.env.NEXT_PUBLIC_SUPABASE_URL||!process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)return null;const s=await createSupabaseServerClient();const{data,error}=await s.from('redirect_rules').select('id,source_path,destination,status_code,active').eq('source_path',sourcePath).eq('active',true).maybeSingle();if(error||!data)return null;return{id:data.id,sourcePath:data.source_path,destination:data.destination,statusCode:data.status_code,active:data.active}}
