import { NextResponse } from 'next/server'
import { requireAdmin } from '@/lib/auth/requireRole'
import { deleteMedia, listMedia, updateMediaMetadata, uploadMedia } from '@/lib/cms/media'
import type { ImageSourceType } from '@/lib/media/imagePolicy'
import { can } from '@/lib/permissions/can'

function hasMediaAccess(admin:{role:'SUPER_ADMIN'|'ADMIN'|'EDITOR';scopes:string[]}){return can(admin.role,'EDIT_CONTENT',admin.scopes,'media')}
const sourceTypes=new Set<ImageSourceType>(['original','licensed','generated'])
function sourceType(value:unknown):ImageSourceType|undefined{return typeof value==='string'&&sourceTypes.has(value as ImageSourceType)?value as ImageSourceType:undefined}
function nullableNumber(value:unknown):number|null|undefined{if(value===undefined)return undefined;if(value===null||value==='')return null;const n=Number(value);return Number.isFinite(n)?n:undefined}

export async function GET(request:Request){const admin=await requireAdmin();if(!hasMediaAccess(admin))return NextResponse.json({error:'FORBIDDEN'},{status:403});const q=new URL(request.url).searchParams.get('q')??'';return NextResponse.json({items:await listMedia(q)})}
export async function POST(request:Request){const admin=await requireAdmin();if(!hasMediaAccess(admin))return NextResponse.json({error:'FORBIDDEN'},{status:403});const form=await request.formData();const file=form.get('file');if(!(file instanceof File))return NextResponse.json({error:'FILE_REQUIRED'},{status:400});const requestedSource=sourceType(form.get('sourceType'));if(form.get('sourceType')&&!requestedSource)return NextResponse.json({error:'INVALID_MEDIA_SOURCE_TYPE'},{status:400});try{return NextResponse.json({item:await uploadMedia(file,admin.userId,{sourceType:requestedSource})},{status:201})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'UPLOAD_FAILED'},{status:400})}}
export async function PATCH(request:Request){const admin=await requireAdmin();if(!hasMediaAccess(admin))return NextResponse.json({error:'FORBIDDEN'},{status:403});const body=await request.json() as Record<string,unknown>;if(typeof body.id!=='string'||typeof body.altText!=='string')return NextResponse.json({error:'INVALID_METADATA'},{status:400});const requestedSource=body.sourceType===undefined?undefined:sourceType(body.sourceType);if(body.sourceType!==undefined&&!requestedSource)return NextResponse.json({error:'INVALID_MEDIA_SOURCE_TYPE'},{status:400});try{const item=await updateMediaMetadata(body.id,{altText:body.altText,caption:typeof body.caption==='string'?body.caption:undefined,tags:Array.isArray(body.tags)?body.tags.filter((tag):tag is string=>typeof tag==='string'):undefined,sourceType:requestedSource,rightsNote:typeof body.rightsNote==='string'||body.rightsNote===null?body.rightsNote as string|null:undefined,focalX:nullableNumber(body.focalX),focalY:nullableNumber(body.focalY),visualQaApproved:typeof body.visualQaApproved==='boolean'?body.visualQaApproved:undefined});return NextResponse.json({ok:true,item})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'MEDIA_UPDATE_FAILED'},{status:400})}}
export async function DELETE(request:Request){const admin=await requireAdmin();if(!hasMediaAccess(admin))return NextResponse.json({error:'FORBIDDEN'},{status:403});const id=new URL(request.url).searchParams.get('id');if(!id)return NextResponse.json({error:'ID_REQUIRED'},{status:400});try{await deleteMedia(id);return NextResponse.json({ok:true})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'DELETE_FAILED'},{status:400})}}
